import { z } from "zod";
import { db } from "../../config/database.js";
import { logger } from "../../utils/logger.js";
import { llm } from "../../llm/model.js";
import { examinerQuizPrompt } from "../../llm/prompts/examiner/examiner.prompt.js";
import { teacherService } from "../teacher/teacher.service.js";
import { coachService } from "../coach/coach.service.js";

/**
 * Zod schema for structured quiz outputs generated by the Examiner Agent.
 */
export const examinerQuizSchema = z.object({
  questions: z.array(
    z.object({
      question: z.string().describe("The quiz question text"),
      options: z.array(z.string()).describe("4 multiple choice options"),
      correct: z.string().describe("The exact text of the correct option"),
      explanation: z.string().describe("Explanation for why this option is correct"),
    })
  ),
});

export const examinerService = {
  /**
   * Examiner Agent: Generates a 3-question evaluation quiz for a lesson.
   */
  async getOrGenerateQuiz(lessonId: string) {
    logger.info(`[ExaminerAgent] Fetching or generating quiz for lessonId [${lessonId}]`);

    // Check if QUIZ activity already exists for this lesson
    const existingQuiz = await db.activity.findFirst({
      where: { lessonId, type: "QUIZ" },
    });

    if (existingQuiz && (existingQuiz.payload as any)?.questions?.length > 0) {
      return existingQuiz;
    }

    // Ensure lesson content is available
    const lesson = await teacherService.getOrGenerateLessonContent(lessonId);

    // Call Gemini with structured schema
    const structuredLlm = llm.withStructuredOutput(examinerQuizSchema);
    const formattedPrompt = await examinerQuizPrompt.format({
      lessonTitle: lesson.title,
      lessonContent: lesson.content || "Standard lesson topic overview.",
    });

    const quizOutput = await structuredLlm.invoke(formattedPrompt);

    // Upsert or create Activity record
    let activity;
    if (existingQuiz) {
      activity = await db.activity.update({
        where: { id: existingQuiz.id },
        data: {
          payload: {
            title: `${lesson.title} - Knowledge Evaluation`,
            questions: quizOutput.questions,
          } as any,
        },
      });
    } else {
      activity = await db.activity.create({
        data: {
          lessonId,
          type: "QUIZ",
          payload: {
            title: `${lesson.title} - Knowledge Evaluation`,
            questions: quizOutput.questions,
          } as any,
        },
      });
    }

    // Log checkpoint
    await db.agentLog.create({
      data: {
        lessonId,
        agentName: "ExaminerAgent",
        message: `Examiner Agent compiled ${quizOutput.questions.length}-question evaluation quiz for "${lesson.title}".`,
        level: "INFO",
      },
    });

    logger.info(`[ExaminerAgent] Successfully created quiz activity [${activity.id}] for lesson [${lessonId}]`);
    return activity;
  },

  /**
   * Examiner Agent: Grades user quiz submission and triggers Adaptive Coach analysis.
   */
  async evaluateQuizSubmission(
    activityId: string,
    userAnswers: Record<number, string>
  ) {
    logger.info(`[ExaminerAgent] Grading quiz submission for activityId [${activityId}]`);

    const activity = await db.activity.findUnique({
      where: { id: activityId },
      include: {
        lesson: {
          include: {
            module: {
              include: {
                phase: {
                  include: {
                    curriculum: true,
                  },
                },
              },
            },
          },
        },
      },
    });

    if (!activity || activity.type !== "QUIZ") {
      throw new Error(`Quiz activity not found for ID: ${activityId}`);
    }

    const questions = (activity.payload as any)?.questions || [];
    if (questions.length === 0) {
      throw new Error(`No quiz questions found in activity payload for ID: ${activityId}`);
    }

    let correctCount = 0;
    const breakdown = questions.map((q: any, idx: number) => {
      const selected = userAnswers[idx] || "";
      const isCorrect = selected.trim() === q.correct.trim();
      if (isCorrect) correctCount++;
      return {
        questionIndex: idx,
        question: q.question,
        selected,
        correct: q.correct,
        isCorrect,
        explanation: q.explanation,
      };
    });

    const scorePercentage = Math.round((correctCount / questions.length) * 100);
    const passed = scorePercentage >= 70;

    // Record Attempt in DB
    const attempt = await db.attempt.create({
      data: {
        activityId,
        score: scorePercentage,
        submission: userAnswers as any,
        feedback: breakdown as any,
      },
    });

    // Log checkpoint
    await db.agentLog.create({
      data: {
        lessonId: activity.lessonId,
        agentName: "ExaminerAgent",
        message: `Examiner Agent graded quiz: ${correctCount}/${questions.length} correct (${scorePercentage}%). Outcome: ${passed ? "PASSED" : "FAILED"}.`,
        level: "INFO",
      },
    });

    // Delegate to Adaptive Coach Agent to update curriculum status or inject remediation
    const goalId = activity.lesson.module.phase.curriculum.goalId;
    const coachResult = await coachService.processQuizOutcome(
      goalId,
      activity.lessonId,
      scorePercentage
    );

    return {
      attemptId: attempt.id,
      scorePercentage,
      passed,
      correctCount,
      totalQuestions: questions.length,
      breakdown,
      coachOutcome: coachResult,
    };
  },
};
